version: '3.7'

services:
  zero9-server:
    image: reg.brian-hong.tech/zero9/zero9-server:latest
    platform: linux/arm64/v8
    container_name: zero9-server
    restart: always
    ports:
      - 5050:3000
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Seoul
    networks:
      - zero9-network

  zero9-redis:
    image: redis:latest
    container_name: zero9-redis
    restart: always
    ports:
      - 6479:6379
    volumes:
      - zero9-redis:/data
    environment:
      - TZ=Asia/Seoul
    networks:
      - zero9-network

volumes:
  zero9-redis:

networks:
  zero9-server:
    driver: bridge
